#
# Maven sets JAVA_HOME aka java.home to ${JAVA_HOME}/jre.  Need to add a funky include for this.
#

CFLAGS=-g -I${JAVA_HOME}/include -I${JAVA_HOME}/include/darwin -I/Users/ngraham/libfabric-cray/include/rdma \
	-I/Users/ngraham/libfabric-cray/include

LDFLAGS= #-ldl

C_SOURCES = 		\
	av_type.c		\
	mr_mode.c		\
	progress.c		\
	threading.c		\
	resource_mgmt.c	\
	ep_type.c		\
	protocol.c		\
	fabric.c		\
	libfabric.c		\
	domain_attr.c	\
	ep_attr.c		\
	fabric_attr.c	\
	receive_attr.c	\
	tx_attr.c

O_FILES =			\
	av_type.o		\
	mr_mode.o		\
	progress.o		\
	threading.o		\
	resource_mgmt.o	\
	ep_type.o		\
	protocol.o		\
	fabric.o		\
	libfabric.o		\
	domain_attr.o	\
	ep_attr.o		\
	fabric_attr.o	\
	receive_attr.c	\
	tx_attr.o

all: libjfab_native.dylib

libjfab_native.dylib: av_type.o
	gcc ${CFLAGS} -dynamiclib ${O_FILES} -o libjfab_native.dylib  ${LDFLAGS}

${O_FILES}: ${C_SOURCES}
	gcc -c ${CFLAGS} ${C_SOURCES}

clean:
	rm -f *.class *.o
	rm -f libhello.so
	rm -f org_*.h

#test:
#	javac -g -Xlint:deprecation -classpath ${CLASSPATH} Test.java