/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ofi_libjfabric_enums_AVType */

#ifndef _Included_org_ofi_libjfabric_enums_AVType
#define _Included_org_ofi_libjfabric_enums_AVType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ofi_libjfabric_enums_AVType
 * Method:    getUNSPEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_AVType_getUNSPEC
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_AVType
 * Method:    getMAP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_AVType_getMAP
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_AVType
 * Method:    getTABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_AVType_getTABLE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
