/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ofi_libjfabric_enums_EPType */

#ifndef _Included_org_ofi_libjfabric_enums_EPType
#define _Included_org_ofi_libjfabric_enums_EPType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ofi_libjfabric_enums_EPType
 * Method:    getUNSPEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_EPType_getUNSPEC
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_EPType
 * Method:    getMSG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_EPType_getMSG
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_EPType
 * Method:    getDGRAM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_EPType_getDGRAM
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_EPType
 * Method:    getRDM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_EPType_getRDM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
