/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ofi_libjfabric_enums_Threading */

#ifndef _Included_org_ofi_libjfabric_enums_Threading
#define _Included_org_ofi_libjfabric_enums_Threading
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ofi_libjfabric_enums_Threading
 * Method:    getUNSPEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Threading_getUNSPEC
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Threading
 * Method:    getSAFE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Threading_getSAFE
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Threading
 * Method:    getFID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Threading_getFID
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Threading
 * Method:    getDOMAIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Threading_getDOMAIN
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Threading
 * Method:    getCOMPLETION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Threading_getCOMPLETION
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Threading
 * Method:    getENDPOINT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Threading_getENDPOINT
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
