/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ofi_libjfabric_enums_MRMode */

#ifndef _Included_org_ofi_libjfabric_enums_MRMode
#define _Included_org_ofi_libjfabric_enums_MRMode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ofi_libjfabric_enums_MRMode
 * Method:    getUNSPEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_MRMode_getUNSPEC
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_MRMode
 * Method:    getBASIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_MRMode_getBASIC
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_MRMode
 * Method:    getSCALABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_MRMode_getSCALABLE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
