/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ofi_libjfabric_enums_Protocol */

#ifndef _Included_org_ofi_libjfabric_enums_Protocol
#define _Included_org_ofi_libjfabric_enums_Protocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ofi_libjfabric_enums_Protocol
 * Method:    getUNSPEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Protocol_getUNSPEC
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Protocol
 * Method:    getRDMA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Protocol_getRDMA
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Protocol
 * Method:    getIWARP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Protocol_getIWARP
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Protocol
 * Method:    getIBUD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Protocol_getIBUD
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Protocol
 * Method:    getPSMX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Protocol_getPSMX
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Protocol
 * Method:    getUDP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Protocol_getUDP
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Protocol
 * Method:    getSOCKTCP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Protocol_getSOCKTCP
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Protocol
 * Method:    getGNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Protocol_getGNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
