/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ofi_libjfabric_enums_ResourceMgmt */

#ifndef _Included_org_ofi_libjfabric_enums_ResourceMgmt
#define _Included_org_ofi_libjfabric_enums_ResourceMgmt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ofi_libjfabric_enums_ResourceMgmt
 * Method:    getUNSPEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_ResourceMgmt_getUNSPEC
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_ResourceMgmt
 * Method:    getDISABLED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_ResourceMgmt_getDISABLED
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_ResourceMgmt
 * Method:    getENABLED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_ResourceMgmt_getENABLED
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
