/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ofi_libjfabric_enums_Progress */

#ifndef _Included_org_ofi_libjfabric_enums_Progress
#define _Included_org_ofi_libjfabric_enums_Progress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ofi_libjfabric_enums_Progress
 * Method:    getUNSPEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Progress_getUNSPEC
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Progress
 * Method:    getAUTO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Progress_getAUTO
  (JNIEnv *, jclass);

/*
 * Class:     org_ofi_libjfabric_enums_Progress
 * Method:    getMANUAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ofi_libjfabric_enums_Progress_getMANUAL
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
